name: learn_language
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  cupertino_icons: ^1.0.8
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.5
  whisper_kit: ^0.3.0
  record: ^6.2.0
  injectable: ^2.7.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/models/vits-piper-en_US-amy-low/
  #   - assets/models/vits-piper-hi_IN-pratham-medium/
  #   - assets/models/espeak-ng-data.zip
